trigger:
  branches:
    include:
      - main  # Change selon ta branche principale

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Installer Java 17
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Exécuter les tests unitaires avec Maven, excluant SpringpaymentEcomApplicationTests
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-Dtest=!EcommerceApplicationTests'  # Exclut le test SpringpaymentEcomApplicationTests
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'